// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Enquiry struct {
	ID          int32
	UserID      int32
	PropertyID  int32
	EnquiryDate time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Property struct {
	ID         int32
	Name       string
	Location   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	FudousanID int32
}

type Schedule struct {
	ID            int32
	UserID        int32
	TaskType      string
	TaskDetails   json.RawMessage
	ScheduledTime string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID                     int32
	Email                  string
	Name                   string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	EnquiryCount           sql.NullInt32
	AvailableTimings       string
	PreferredContactMethod string
}
