// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: properties.sql

package database

import (
	"context"
)

const getAPropertyDetailsById = `-- name: GetAPropertyDetailsById :one
SELECT name, location
FROM properties
WHERE id = $1
`

type GetAPropertyDetailsByIdRow struct {
	Name     string
	Location string
}

func (q *Queries) GetAPropertyDetailsById(ctx context.Context, id int32) (GetAPropertyDetailsByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAPropertyDetailsById, id)
	var i GetAPropertyDetailsByIdRow
	err := row.Scan(&i.Name, &i.Location)
	return i, err
}
