// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.26.1
// source: enquiries.proto

package enquiries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerEnquiry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyId       int32  `protobuf:"varint,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Name             string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location         string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	PreferredMethod  string `protobuf:"bytes,5,opt,name=preferred_method,json=preferredMethod,proto3" json:"preferred_method,omitempty"`
	AvailableTimings string `protobuf:"bytes,6,opt,name=available_timings,json=availableTimings,proto3" json:"available_timings,omitempty"`
	FudousanId       int32  `protobuf:"varint,7,opt,name=fudousan_id,json=fudousanId,proto3" json:"fudousan_id,omitempty"`
}

func (x *CustomerEnquiry) Reset() {
	*x = CustomerEnquiry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiries_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerEnquiry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerEnquiry) ProtoMessage() {}

func (x *CustomerEnquiry) ProtoReflect() protoreflect.Message {
	mi := &file_enquiries_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerEnquiry.ProtoReflect.Descriptor instead.
func (*CustomerEnquiry) Descriptor() ([]byte, []int) {
	return file_enquiries_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerEnquiry) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CustomerEnquiry) GetPropertyId() int32 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *CustomerEnquiry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerEnquiry) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CustomerEnquiry) GetPreferredMethod() string {
	if x != nil {
		return x.PreferredMethod
	}
	return ""
}

func (x *CustomerEnquiry) GetAvailableTimings() string {
	if x != nil {
		return x.AvailableTimings
	}
	return ""
}

func (x *CustomerEnquiry) GetFudousanId() int32 {
	if x != nil {
		return x.FudousanId
	}
	return 0
}

type CustomerEnquiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enquiry *CustomerEnquiry `protobuf:"bytes,1,opt,name=enquiry,proto3" json:"enquiry,omitempty"`
}

func (x *CustomerEnquiryRequest) Reset() {
	*x = CustomerEnquiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiries_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerEnquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerEnquiryRequest) ProtoMessage() {}

func (x *CustomerEnquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enquiries_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerEnquiryRequest.ProtoReflect.Descriptor instead.
func (*CustomerEnquiryRequest) Descriptor() ([]byte, []int) {
	return file_enquiries_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerEnquiryRequest) GetEnquiry() *CustomerEnquiry {
	if x != nil {
		return x.Enquiry
	}
	return nil
}

type CustomerEnquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CustomerEnquiryResponse) Reset() {
	*x = CustomerEnquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enquiries_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerEnquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerEnquiryResponse) ProtoMessage() {}

func (x *CustomerEnquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enquiries_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerEnquiryResponse.ProtoReflect.Descriptor instead.
func (*CustomerEnquiryResponse) Descriptor() ([]byte, []int) {
	return file_enquiries_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerEnquiryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CustomerEnquiryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_enquiries_proto protoreflect.FileDescriptor

var file_enquiries_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69, 0x65, 0x73, 0x22, 0xf4, 0x01, 0x0a,
	0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x75, 0x64, 0x6f, 0x75, 0x73, 0x61, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x75, 0x64, 0x6f, 0x75, 0x73, 0x61,
	0x6e, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x07, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75,
	0x69, 0x72, 0x79, 0x22, 0x4d, 0x0a, 0x17, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45,
	0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x70, 0x0a, 0x0e, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x12, 0x21, 0x2e,
	0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x65, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x69,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enquiries_proto_rawDescOnce sync.Once
	file_enquiries_proto_rawDescData = file_enquiries_proto_rawDesc
)

func file_enquiries_proto_rawDescGZIP() []byte {
	file_enquiries_proto_rawDescOnce.Do(func() {
		file_enquiries_proto_rawDescData = protoimpl.X.CompressGZIP(file_enquiries_proto_rawDescData)
	})
	return file_enquiries_proto_rawDescData
}

var file_enquiries_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_enquiries_proto_goTypes = []interface{}{
	(*CustomerEnquiry)(nil),         // 0: enquiries.CustomerEnquiry
	(*CustomerEnquiryRequest)(nil),  // 1: enquiries.CustomerEnquiryRequest
	(*CustomerEnquiryResponse)(nil), // 2: enquiries.CustomerEnquiryResponse
}
var file_enquiries_proto_depIdxs = []int32{
	0, // 0: enquiries.CustomerEnquiryRequest.enquiry:type_name -> enquiries.CustomerEnquiry
	1, // 1: enquiries.EnquiryService.HandleCustomerEnquiry:input_type -> enquiries.CustomerEnquiryRequest
	2, // 2: enquiries.EnquiryService.HandleCustomerEnquiry:output_type -> enquiries.CustomerEnquiryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enquiries_proto_init() }
func file_enquiries_proto_init() {
	if File_enquiries_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enquiries_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerEnquiry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enquiries_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerEnquiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enquiries_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerEnquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enquiries_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enquiries_proto_goTypes,
		DependencyIndexes: file_enquiries_proto_depIdxs,
		MessageInfos:      file_enquiries_proto_msgTypes,
	}.Build()
	File_enquiries_proto = out.File
	file_enquiries_proto_rawDesc = nil
	file_enquiries_proto_goTypes = nil
	file_enquiries_proto_depIdxs = nil
}
