// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Log struct {
	ID          int32
	ServiceName string
	LogData     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
